name = "email-to-rss"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# KV Namespace bindings
kv_namespaces = [
  { binding = "EMAIL_STORAGE", id = "721e2789af9a41eba56a77e7891fd85a", preview_id = "b741d3713dd0416ca80b34ae6539736e" }
]

# Environment variables
[vars]
ADMIN_PASSWORD = ""  # Set this using wrangler secret
DOMAIN = "getmynews.app"  # Your custom domain for emails

# Development environment
[env.dev]
# Add any development-specific configuration here
workers_dev = true

# Production environment
[env.production]
# Add any production-specific configuration here
workers_dev = false
routes = [
  "https://getmynews.app/*",
  "https://www.getmynews.app/*"
] 